version: '3.4'

services:
  origin:
    image: pijoe/ome-auth:latest
    ports:
    - "1935:1935/tcp"
    - "3333:3333/tcp"
    - "9000:9000/tcp"
    - "4000-4005:4000-4005/udp"
    - "10006-10010:10006-10010/udp"
    environment:
    - OME_RTMP_PROV_PORT=1935
    - OME_SIGNALLING_PORT=3333
    - OME_MPEGTS_PROV_PORT=4000-4005/udp
    - OME_ICE_CANDIDATES=*:10006-10010/udp
    - DEFAULT_ORIGIN_SERVER=192.168.0.222
    volumes:
    - ./conf/:/var/conf
    command: /opt/ovenmediaengine/bin/OvenMediaEngine -c /var/conf